name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
  pull_request: # Also run on pull requests for pre-merge testing
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Grant write permission to the packages scope for pushing images

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Using a later, more stable version tag

      - name: Log in to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5 # Using a later, more stable version tag
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/shared-secret:latest
          file: ./Dockerfile
          cache-from: type=gha # Use GHA cache for faster builds
          cache-to: type=gha,mode=max # Save new layers to the cache
